DROP TRIGGER fix_courses ON ADMINISTRATOR;
DROP FUNCTION fix_courses();

DROP TABLE PUPIL_COURSE;
DROP TABLE ADMIN_COURSE;
DROP TABLE PUPIL CASCADE;
DROP TABLE COURSE CASCADE;
DROP TABLE LESSON CASCADE;
DROP TABLE TEACHER CASCADE;
DROP TABLE ADMINISTRATOR CASCADE;